"""normalize fyp ideas

Revision ID: c778823a12e7
Revises: abc00f54aa42
Create Date: 2026-07-05 10:35:58.304198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c778823a12e7'
down_revision: Union[str, Sequence[str], None] = 'abc00f54aa42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idea_skills',
    sa.Column('idea_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['idea_id'], ['fyp_ideas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('idea_technologies',
    sa.Column('idea_id', sa.UUID(), nullable=False),
    sa.Column('technology_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['idea_id'], ['fyp_ideas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['technology_id'], ['technologies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('fyp_ideas', sa.Column('domain_id', sa.UUID(), nullable=False))
    op.add_column('fyp_ideas', sa.Column('difficulty', sa.String(length=30), nullable=False))
    op.create_foreign_key(None, 'fyp_ideas', 'domains', ['domain_id'], ['id'])
    op.drop_column('fyp_ideas', 'technologies')
    op.drop_column('fyp_ideas', 'department')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fyp_ideas', sa.Column('department', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('fyp_ideas', sa.Column('technologies', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'fyp_ideas', type_='foreignkey')
    op.drop_column('fyp_ideas', 'difficulty')
    op.drop_column('fyp_ideas', 'domain_id')
    op.drop_table('idea_technologies')
    op.drop_table('idea_skills')
    # ### end Alembic commands ###
